# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
     database_controller:
         class: AppBundle\Utils\CategoriesPktUtils
         calls:
            - [setContainer, ["@doctrine.orm.entity_manager"]]
